services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - "/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
  php:
    image: php-mysql
    ports:
      - "8000:8000"
    volumes:
      - "./:/usr/src/app/"
    command: php artisan serve --host 0.0.0.0 --port 8000
    working_dir: /usr/src/app
  node:
    image: node:22
    ports:
      - "5173:5173"
    volumes:
      - "./:/home/node/app"
    working_dir: /home/node/app
    user: "node"
    command: npm run dev -- --host
    stdin_open: true
    tty: true

